name: Deploy

on:
  push:
    branches: [ master ]
  # Can be activated manually
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # https://github.com/marketplace/actions/dokku-deploy-action?version=v1
    - name: Push to sips
      uses: idoberko2/dokku-deploy-github-action@v1
      with:
        ssh-private-key: ${{ secrets.SIPS_SSH_KEY }}
        dokku-user: 'dokku'
        remote-branch: 'master'
        dokku-host: 'sips.datasektionen.se'
        app-name: 'ddagen'